<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>Pulse</title>
	<link href="css/stylus.css" rel="stylesheet" type="text/css" />
	<link href="css/common_master.css" rel="stylesheet" type="text/css" />
	<link href="css/font.css" rel="stylesheet" type="text/css" />
	<!--<meta http-equiv="refresh" content="01"/>-->
</head>

<body>
	
	<?php include "core/header.core.php"; ?>
	
	
	
<div class="wrapper">
	
	<div class="col-wrapper">
		
		<?php include "core/sidebarmenu.core.php"; ?>
		
		<div class="full-column db-cont-wrap right">
		
			<div class="column-head">
				<div class="left pageback"><a href="#"><img src="img/back.svg" alt="" width="18px"></a></div>
				<div class="col-pagename left">Clinic Profile</div>
				<div class="master-creation right"><a href="#"><span class="crticn"><img src="img/edit.svg" alt="" width="16px"></span><span class="crtxt">Edit Information</span><div class="clr"></div></a></div>
				<div class="clr"></div>
			</div>
			
			<div class="content-page boxsizing">
				
			<div class="view-mode">
				<p class="left">Clinic Name</p>
				<span>S.M. Neurology Clinic</span>
				<div class="clr"></div>
			</div>
			
			<div class="view-mode">
				<p class="left">Area/Location</p>
				<span>Aminabad</span>
				<div class="clr"></div>
			</div>
				
			<div class="view-mode">
				<p class="left">Clinic Registration No.</p>
				<span>98476847648</span>
				<div class="clr"></div>
			</div>
				
			<div class="view-mode">
				<p class="left">Email</p>
				<span>sm.neurology@gmail.com</span>
				<div class="clr"></div>
			</div>
				
			<div class="view-mode">
				<p class="left">Phone / Mobile</p>
				<span>9890981290</span>
				<div class="clr"></div>
			</div>
				
			<div class="view-mode">
				<p class="left">Address</p>
				<span>Block A, DDA Plot 181 Sector 19, Dwarka, New Delhi, Delhi 110075</span>
				<div class="clr"></div>
			</div>
				
			<div class="view-mode">
				<p class="left">ZIP COde</p>
				<span>567898</span>
				<div class="clr"></div>
			</div>
				
			<div class="view-mode">
				<p class="left">Google Location</p>
				<span><a href="#">https://goo.gl/maps/1ADzreYHkxMcam3q6</a></span>
				<div class="clr"></div>
			</div>
				
			<div class="view-mode">
				<p class="left">Open Days & Timings</p>
				<span>
					Mon: 09AM to 1030 AM<br>
					Tue: 09AM to 1030 AM<br>
					Wed: 09AM to 1030 AM<br>
					Thu: 09AM to 1030 AM<br>
					Fri: 09AM to 1030 AM<br>
					Sat: 09AM to 1030 AM<br>
					Sun: 09AM to 1030 AM
				</span>
				<div class="clr"></div>
			</div>
				
			<div class="view-mode">
				<p class="left">Specialities Available</p>
				<span>
					<div>
					<div class="left dyslctns">
						<span>Pulmonologist</span>
					</div>
					<div class="left dyslctns">
						<span>Oncologist</span>
					</div>
					<div class="left dyslctns">
						<span>General Physician</span>
					</div>
						<div class="left dyslctns">
						<span>Thursday</span>
					</div>
						<div class="left dyslctns">
						<span>Friday</span>
					</div>
					<div class="clr"></div>
						<div class="frm-file-specs tmarg">Autogenerated from the doctor of specilities available in clinic</div>
				</div>
				</span>
				<div class="clr"></div>
			</div>
				
			<div class="view-mode">
				<p class="left">Facilities Available</p>
				<span>
					<div>
					<div class="left dyslctns">
						<span>Parking</span>
					</div>
					<div class="left dyslctns">
						<span>Lounge</span>
					</div>
					<div class="left dyslctns">
						<span>Drinking Water</span>
					</div>
						<div class="left dyslctns">
						<span>Books to Read</span>
					</div>
						<div class="left dyslctns">
						<span>Friday</span>
					</div>
					<div class="clr"></div>
				</div>
				</span>
				<div class="clr"></div>
			</div>
				
			<div class="view-mode">
				<p class="left">Status</p>
				<span class="grntxt">Active</span>
				<div class="clr"></div>
			</div>
				
			<div class="view-mode">
				<p class="left">Username</p>
				<span>clinic0098</span>
				<div class="clr"></div>
			</div>
				
			<div class="view-mode">
				<p class="left">Password</p>
				<span>•••••••• <a href="#">Show Password</a></span>
				<div class="clr"></div>
			</div>
				
			<div class="view-mode">
				<p class="left">Clinic Photos</p>
				<span>
					<div>
										<div class="doc-box-wrap">
									<div class="file-prvw"><img src="img/adhar.png" alt="" width="122px" height="122px"></div>
									
									<div class="file-actns">
										<a href="#"><img src="img/eye.svg" alt="" width="18px"></a>
										<a href="#"><img src="img/download.svg" alt="" width="18px"></a>
										<a href="#"><img src="img/binremove.svg" alt="" width="18px"></a>
									</div>
										</div>
										
										<div class="doc-box-wrap">
									<div class="file-prvw"><img src="img/adhar.png" alt="" width="122px" height="122px"></div>
									
									<div class="file-actns">
										<a href="#"><img src="img/eye.svg" alt="" width="18px"></a>
										<a href="#"><img src="img/download.svg" alt="" width="18px"></a>
										<a href="#"><img src="img/binremove.svg" alt="" width="18px"></a>
									</div>
										</div>
										
										<div class="doc-box-wrap">
									<div class="file-prvw"><img src="img/adhar.png" alt="" width="122px" height="122px"></div>
									
									<div class="file-actns">
										<a href="#"><img src="img/eye.svg" alt="" width="18px"></a>
										<a href="#"><img src="img/download.svg" alt="" width="18px"></a>
										<a href="#"><img src="img/binremove.svg" alt="" width="18px"></a>
									</div>
										</div>
										
										<div class="doc-box-wrap">
									<div class="file-prvw"><img src="img/adhar.png" alt="" width="122px" height="122px"></div>
									
									<div class="file-actns">
										<a href="#"><img src="img/eye.svg" alt="" width="18px"></a>
										<a href="#"><img src="img/download.svg" alt="" width="18px"></a>
										<a href="#"><img src="img/binremove.svg" alt="" width="18px"></a>
									</div>
										</div>
										
										<div class="doc-box-wrap">
									<div class="file-prvw"><img src="img/adhar.png" alt="" width="122px" height="122px"></div>
									
									<div class="file-actns">
										<a href="#"><img src="img/eye.svg" alt="" width="18px"></a>
										<a href="#"><img src="img/download.svg" alt="" width="18px"></a>
										<a href="#"><img src="img/binremove.svg" alt="" width="18px"></a>
									</div>
										</div>
										
										<div class="doc-box-wrap">
									<div class="file-prvw"><img src="img/adhar.png" alt="" width="122px" height="122px"></div>
									
									<div class="file-actns">
										<a href="#"><img src="img/eye.svg" alt="" width="18px"></a>
										<a href="#"><img src="img/download.svg" alt="" width="18px"></a>
										<a href="#"><img src="img/binremove.svg" alt="" width="18px"></a>
									</div>
										</div>
										
										<div class="doc-box-wrap">
									<div class="file-prvw"><img src="img/adhar.png" alt="" width="122px" height="122px"></div>
									
									<div class="file-actns">
										<a href="#"><img src="img/eye.svg" alt="" width="18px"></a>
										<a href="#"><img src="img/download.svg" alt="" width="18px"></a>
										<a href="#"><img src="img/binremove.svg" alt="" width="18px"></a>
									</div>
										</div>
										
										<div class="doc-box-wrap">
									<div class="file-prvw"><img src="img/adhar.png" alt="" width="122px" height="122px"></div>
									
									<div class="file-actns">
										<a href="#"><img src="img/eye.svg" alt="" width="18px"></a>
										<a href="#"><img src="img/download.svg" alt="" width="18px"></a>
										<a href="#"><img src="img/binremove.svg" alt="" width="18px"></a>
									</div>
										</div>
										
										<div class="clr"></div>
						<div class="actionbuttons">
				
				<a href="#" class="primary left rmarg">Upload Photos</a>
							<div class="clr"></div>

			</div>
									</div>
				</span>
				<div class="clr"></div>
			</div>
				
			</div>
			
		</div>
		
		
		
		<div class="clr"></div>
	
<?php include "core/footer.core.php"; ?>
</div>
			
	</div>
	
</body>
</html>